global using $ext_safeprojectname$.Core;
global using $ext_safeprojectname$.UI;
global using $ext_safeprojectname$.Data;
global using Bunit;
global using Xunit;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
